services:
  - type: web
    name: pdf-app-web
    env: static # Usamos un entorno genérico y confiamos en build/start commands
    branch: main
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/pdf-app-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: "dul26l4sd"
      - key: CLOUDINARY_API_KEY
        value: "644893912335333"
      - key: CLOUDINARY_API_SECRET
        value: "B9vTDgb_vZx-9UxXp9Pm6inpEHc"
